config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#main_page' #this is a method! -> when we're on the static page controller, go to the main_page view

  resources :tweets

  resources :profiles #refers to the controller, not an individual profiles

  resources :relationships, only: [:create]

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  mount_uploader :pic, PicUploader
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
#these properties are the intrinsic values of a Tweet
	belongs_to :user #a tweet belongs to a user
	validates :tweet, length: { maximum: 140 }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets # a user has many tweets

  has_one :profile # a user only have ONE profile

  has_many :active_relationships, class_name:  "Relationship",
                                 foreign_key: "follower_id",
                                 dependent:   :destroy

  has_many :passive_relationships, class_name:  "Relationship",
	                   foreign_key: "followed_id",
	                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

 # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

 # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def new
		if current_user.profile
			redirect_to profile_path(current_user.profile)
		else
			@profile = Profile.new
		end
	end

	def create
		@profile = Profile.new(profile_params)
		@profile.user = current_user
		if @profile.save
			flash[:success] = "Your profile successfully created!"
			redirect_to profile_path(current_user)
		else
			flash.now[:danger] = "ERROR: Profile has not been created."
			render 'new'
		end

		
	end



	def show
		@profile = Profile.find(params[:id])
	end

	def profile_params
		params.require(:profile).permit(:description, :pic)
	end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
		#@relationship = Relationship.new(relationship_params)
		#@relationship.follower_id = current_user

		@user = User.find(relationship_params[:followed_id])

		if current_user.follow(@user)
			flash[:success] = "You are now following #{@user.email}" #the #{} shows a variable you're putting in
		else
			flash[:danger] = "The user canot be followed at this time."
		end

		redirect_to tweets_path
	end

	def relationship_params
		params.require(:relationship).permit(:followed_id)
		# sanitize the parameters
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def main_page

	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	before_action :authenticate_user!
	#! -> usually means to raise an error; can also mean that you may be "doing something dangerous"

	def new
		#creates new instance of the object Tweet
		#'@' -> means the view has an access to the variable
		@tweet = Tweet.new
		@tweets = current_user.tweets
		#only shows the tweets that belong to you
		# @tweets = Tweet.all -> variable will hold all the tweets
	end

	# create doesn't have access to the object Tweet since it's not defined here
	def create
		#saves it to database; same as @tweet = Tweet.create(tweet_params) w/ our extra .user 
		@tweet = Tweet.new(tweet_params)
		@tweet.user = current_user
		if @tweet.save
			flash[:success] = "You have successfully created a Tweet!"
		else
			flash[:danger] = "Input isn't correct. Please try again."
		end

		# give create an instance of all the tweets too -> or it can't render
		@tweets = current_user.tweets
		
		#it doesn't need to be rendered on a new page -> just on the same page as the form, the new page
		render 'new'
	end

	def index
		@tweets = Tweet.all.reject {|tweet| tweet.user == current_user}
		@relationship = Relationship.new
	end

	private

	def tweet_params
		#requires the tweet object and only takes in the tweet string
		params.require(:tweet).permit(:tweet)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twipper</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- Nav bar from bootstrap -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Twipper</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <% if !user_signed_in? %>
        	<li>
        		<%= link_to "Sign Up", new_user_registration_path %>
        	</li>
        	<li>
        		<%= link_to "Sign In", new_user_session_path %>
        	</li>

        <% else %>
        	<li>
        		<%= link_to "New Tweet", new_tweet_path %>
        	</li>
        	<li>
        		<%= link_to "Newsfeed", tweets_path %>
        	</li>

        <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
        <% if user_signed_in? %>
        	<li>
        		<%= link_to "My Profile", new_profile_path %>
        	</li>
        	<li> 
        		<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        	</li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/profiles/new.html.erb
New profile form

<%= simple_form_for @profile do |f| %>

	<%= f.input :description %>
	<%= f.input :pic %>
	<%= f.button :submit %>

<% end %>

app/views/profiles/show.html.erb
This is the profile for <%= @profile.user.email %>
<%= image_tag @profile.pic %>

app/views/static_pages/main_page.html.erb
this is the main page

app/views/tweets/index.html.erb
<h3>What has everyone else been up to?</h3>
<ul>
	<% @tweets.each do |tweet| %>
		<li><%= tweet.user.email %> || <%= tweet.tweet %>
			<% if current_user.following?(tweet.user) %>
				<button type="button" class="btn btn-danger">
					Already Following
				</button>
			<% else %>
				<%= simple_form_for @relationship do |f| %>
					<%= f.input :followed_id, as: :hidden, input_html: { value: tweet.user.id } %>
					<%= f.button :submit, "Follow", class: 'btn btn-primary' %>
				<% end %>
			<% end %>
		</li>
		<br>
	<% end %>
</ul>

app/views/tweets/new.html.erb
<%= simple_form_for @tweet do |f| %>
  <%= f.input :tweet, label: "Say something:" %>
  <!-- :tweet is the same as putting 'tweet' -->
  <%= f.button :submit %>
<% end %>

<!-- %= -> outputs the results (returns a string that is outputted as HTML)
	 %  -> doesn't output anything; just ends a loop or something           -->

<h3>What have you Tweeted?</h3>
<uL>
	<!-- |tweet| is what we're calling each object -->
	<% @tweets.each do |tweet| %>
		<!-- get the tweet string (attribute) in the tweet model -->
		<li><%= tweet.tweet %></li>
	<% end %>
</ul>